// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using TozawaNGO.Context;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TozawaNGO.MyCompiledModels
{
    [DbContext(typeof(TozawangoDbContext))]
    public partial class TozawangoDbContextModel : RuntimeModel
    {
        static TozawangoDbContextModel()
        {
            var model = new TozawangoDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static TozawangoDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
