//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TozawaMauiHybrid.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TozawaMauiHybrid.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string _06e63f65_c762_4650_ba32_b177aa26459f {
            get {
                return ResourceManager.GetString("06e63f65-c762-4650-ba32-b177aa26459f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        public static string _07b78220_ec36_4215_bb32_e2b1b4a0b580 {
            get {
                return ResourceManager.GetString("07b78220-ec36-4215-bb32-e2b1b4a0b580", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail us.
        /// </summary>
        public static string _08933bdd_7275_4a80_bf3c_79226cded894 {
            get {
                return ResourceManager.GetString("08933bdd-7275-4a80-bf3c-79226cded894", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please the file name is too large, use max 255 characters as recommanded.
        /// </summary>
        public static string _09e30fc1_245a_46b6_bf2a_dafd00039e5b {
            get {
                return ResourceManager.GetString("09e30fc1-245a-46b6-bf2a-dafd00039e5b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name should be alpha numeric.
        /// </summary>
        public static string _0a12f107_5899_4410_9820_c70e5c26acb7 {
            get {
                return ResourceManager.GetString("0a12f107-5899-4410-9820-c70e5c26acb7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show deleted items.
        /// </summary>
        public static string _10cba804_b8b6_49e2_b3b6_b96fdea1035f {
            get {
                return ResourceManager.GetString("10cba804-b8b6-49e2-b3b6-b96fdea1035f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string _195E79A9_F767_4246_8D30_BB8A834B07C0 {
            get {
                return ResourceManager.GetString("195E79A9-F767-4246-8D30-BB8A834B07C0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string _1bb7f155_e280_4f99_bb8f_047e451a3409 {
            get {
                return ResourceManager.GetString("1bb7f155-e280-4f99-bb8f-047e451a3409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string _1c670beb_c72a_41a3_bd15_8d0dae88c0a1 {
            get {
                return ResourceManager.GetString("1c670beb-c72a-41a3-bd15-8d0dae88c0a1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity contains no files.
        /// </summary>
        public static string _1f4ca531_ca3c_4a33_bb20_ff1f0d46b62a {
            get {
                return ResourceManager.GetString("1f4ca531-ca3c-4a33-bb20-ff1f0d46b62a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a member.
        /// </summary>
        public static string _2042a238_8375_4596_8f59_58d7fbf65d3c {
            get {
                return ResourceManager.GetString("2042a238-8375-4596-8f59-58d7fbf65d3c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the email exists already..
        /// </summary>
        public static string _28dab09a_c496_40e3_9854_79d7ea96557b {
            get {
                return ResourceManager.GetString("28dab09a-c496-40e3-9854-79d7ea96557b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists.
        /// </summary>
        public static string _2d49ea8a_6935_42bb_b482_84c3c7ad608e {
            get {
                return ResourceManager.GetString("2d49ea8a-6935-42bb-b482-84c3c7ad608e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 10 files can be uploaded at a moment.
        /// </summary>
        public static string _2eac4ad7_ada7_48a0_a4ab_a985820140e4 {
            get {
                return ResourceManager.GetString("2eac4ad7-ada7-48a0-a4ab-a985820140e4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string _2f21ae24_6168_4047_8ab2_db1849b3868e {
            get {
                return ResourceManager.GetString("2f21ae24-6168-4047-8ab2-db1849b3868e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This NGO is for helping children in need of developing computer skills This NGO is for helping children in need of developing computer skills This NGO is for helping children in need of developing computer skills
        ///	.
        /// </summary>
        public static string _2f2544a2_82f4_456d_be26_4fd01a7a60b0 {
            get {
                return ResourceManager.GetString("2f2544a2-82f4-456d-be26-4fd01a7a60b0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string _2f2cad45_d815_41a1_b29d_121d3bd813a1 {
            get {
                return ResourceManager.GetString("2f2cad45-d815-41a1-b29d-121d3bd813a1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string _36824adb_80d4_480c_b8fb_474e445673cb {
            get {
                return ResourceManager.GetString("36824adb-80d4-480c-b8fb-474e445673cb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string _3cf9101d_15bb_4481_9094_8009b7c92dff {
            get {
                return ResourceManager.GetString("3cf9101d-15bb-4481-9094-8009b7c92dff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string _45e5f7fa_7fa5_4b5a_9504_27eabb9acded {
            get {
                return ResourceManager.GetString("45e5f7fa-7fa5-4b5a-9504-27eabb9acded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No maching records.
        /// </summary>
        public static string _51353e2a_00db_4b36_be2a_edb59634bbb8 {
            get {
                return ResourceManager.GetString("51353e2a-00db-4b36-be2a-edb59634bbb8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address..
        /// </summary>
        public static string _536bac48_29c2_4d97_a20d_9e5c85b94933 {
            get {
                return ResourceManager.GetString("536bac48-29c2-4d97-a20d-9e5c85b94933", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string _640642e8_c339_4f62_9b5c_58821061d49c {
            get {
                return ResourceManager.GetString("640642e8-c339-4f62-9b5c-58821061d49c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment type.
        /// </summary>
        public static string _65ff3356_f87b_43e9_8228_7d757f5bcea9 {
            get {
                return ResourceManager.GetString("65ff3356-f87b-43e9-8228-7d757f5bcea9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string _693242ad_7369_4f5d_ad44_881240770d31 {
            get {
                return ResourceManager.GetString("693242ad-7369-4f5d-ad44-881240770d31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temporarly.
        /// </summary>
        public static string _6acec748_2d76_4491_8b77_fd9f990d158a {
            get {
                return ResourceManager.GetString("6acec748-2d76-4491-8b77-fd9f990d158a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to ge logged ou.
        /// </summary>
        public static string _6c12b3d5_3661_42ff_b97a_74e0a5b2102e {
            get {
                return ResourceManager.GetString("6c12b3d5-3661-42ff-b97a-74e0a5b2102e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish Association for International Work in Technology and Informatics.
        /// </summary>
        public static string _6d10c11a_9e10_4ea2_ab28_b4c9280b5b62 {
            get {
                return ResourceManager.GetString("6d10c11a-9e10-4ea2-ab28-b4c9280b5b62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        public static string _723f9da4_2551_4120_871a_1fc96554a3d7 {
            get {
                return ResourceManager.GetString("723f9da4-2551-4120-871a-1fc96554a3d7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string _753c584a_789b_409d_8e9e_89ccac2f0e7d {
            get {
                return ResourceManager.GetString("753c584a-789b-409d-8e9e-89ccac2f0e7d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string _778aaa56_c345_4336_93ea_1d866d243a49 {
            get {
                return ResourceManager.GetString("778aaa56-c345-4336-93ea-1d866d243a49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string _78e6d2df_ee8d_485f_a7a0_182a33c45988 {
            get {
                return ResourceManager.GetString("78e6d2df-ee8d-485f-a7a0-182a33c45988", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows per page.
        /// </summary>
        public static string _79396871_e984_4746_953a_4dd28cd8c445 {
            get {
                return ResourceManager.GetString("79396871-e984-4746-953a-4dd28cd8c445", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string _7c06ef7d_12f5_4875_8335_fdfd41c55b36 {
            get {
                return ResourceManager.GetString("7c06ef7d-12f5-4875-8335-fdfd41c55b36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        public static string _7d1747ad_b243_40ec_a1ee_43cab5af5012 {
            get {
                return ResourceManager.GetString("7d1747ad-b243-40ec-a1ee-43cab5af5012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay loged in.
        /// </summary>
        public static string _7f1a951d_82e3_4bda_aa5b_011f0552cd22 {
            get {
                return ResourceManager.GetString("7f1a951d-82e3-4bda-aa5b-011f0552cd22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usefull links.
        /// </summary>
        public static string _84d2a41e_bd0e_49ab_9ec5_245da8794e26 {
            get {
                return ResourceManager.GetString("84d2a41e-bd0e-49ab-9ec5-245da8794e26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string _84e48e74_3760_4f08_8c75_e98bb728b9ee {
            get {
                return ResourceManager.GetString("84e48e74-3760-4f08-8c75-e98bb728b9ee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the file type is not valid, only images pdf word textfile and excel are allowed.
        /// </summary>
        public static string _9ec2bab4_4b69_4c6d_aa8c_a8fbe79fe88b {
            get {
                return ResourceManager.GetString("9ec2bab4-4b69-4c6d-aa8c-a8fbe79fe88b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Allowed maximum size is.
        /// </summary>
        public static string a3305de1_7c44_4c74_bc4f_5c1dc65195ce {
            get {
                return ResourceManager.GetString("a3305de1-7c44-4c74-bc4f-5c1dc65195ce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password cannot be empty.
        /// </summary>
        public static string a43816d6_0f37_4b29_8271_5ca720b094d5 {
            get {
                return ResourceManager.GetString("a43816d6-0f37-4b29-8271-5ca720b094d5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call us.
        /// </summary>
        public static string a5836384_37d4_439c_a627_ee8b989722db {
            get {
                return ResourceManager.GetString("a5836384-37d4-439c-a627-ee8b989722db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string a7cdd2fe_1371_4b44_a996_96e647b834ef {
            get {
                return ResourceManager.GetString("a7cdd2fe-1371-4b44-a996-96e647b834ef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find us.
        /// </summary>
        public static string aabd1818_fd10_41d0_8ad5_8c0d12e205d4 {
            get {
                return ResourceManager.GetString("aabd1818-fd10-41d0-8ad5-8c0d12e205d4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ad71d9fe_67aa_4b8a_8661_1c603e4ec35a {
            get {
                return ResourceManager.GetString("ad71d9fe-67aa-4b8a-8661-1c603e4ec35a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string ae2a4ae2_0b77_4038_80f1_8e6811ef184a {
            get {
                return ResourceManager.GetString("ae2a4ae2-0b77-4038-80f1-8e6811ef184a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string b752a56a_f067_4937_ae38_ac8d496d6413 {
            get {
                return ResourceManager.GetString("b752a56a-f067-4937-ae38-ac8d496d6413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string ba415f27_755f_4293_ab4e_71af9fb48983 {
            get {
                return ResourceManager.GetString("ba415f27-755f-4293-ab4e-71af9fb48983", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to definitly.
        /// </summary>
        public static string bf4c3434_3575_460a_86e2_b757cbdbec07 {
            get {
                return ResourceManager.GetString("bf4c3434-3575-460a-86e2-b757cbdbec07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string c14a265b_0c57_4594_b464_6d22bab412f7 {
            get {
                return ResourceManager.GetString("c14a265b-0c57-4594-b464-6d22bab412f7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string c43eaa7e_3016_420f_8c6a_70c26d82a223 {
            get {
                return ResourceManager.GetString("c43eaa7e-3016-420f-8c6a-70c26d82a223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string cd04b055_c8c3_46c1_aa5d_d962a30f15f1 {
            get {
                return ResourceManager.GetString("cd04b055-c8c3-46c1-aa5d-d962a30f15f1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string d2ff9654_fd31_4cbf_8c52_6ae071d38371 {
            get {
                return ResourceManager.GetString("d2ff9654-fd31-4cbf-8c52-6ae071d38371", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid email is required.
        /// </summary>
        public static string d3903b12_c2ff_4dac_9547_851d37f855bc {
            get {
                return ResourceManager.GetString("d3903b12-c2ff-4dac-9547-851d37f855bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string d9cbe699_7270_4b9d_ac74_377f82cbc85c {
            get {
                return ResourceManager.GetString("d9cbe699-7270-4b9d-ac74-377f82cbc85c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure.
        /// </summary>
        public static string db338fe8_8657_492b_9e82_6b44b0bc1252 {
            get {
                return ResourceManager.GetString("db338fe8-8657-492b-9e82-6b44b0bc1252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string db52be9f_8189_42c2_8dd3_1609caa03173 {
            get {
                return ResourceManager.GetString("db52be9f-8189-42c2-8dd3-1609caa03173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string e2d165ce_741d_4388_a7fa_0e104dc94504 {
            get {
                return ResourceManager.GetString("e2d165ce-741d-4388-a7fa-0e104dc94504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t miss to subscribe to our feeds, kindly fill the form below.
        /// </summary>
        public static string e7dc189c_2a4c_417b_b766_addc69ae7f93 {
            get {
                return ResourceManager.GetString("e7dc189c-2a4c-417b-b766-addc69ae7f93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string e840168a_123d_441d_855c_69ae27d18078 {
            get {
                return ResourceManager.GetString("e840168a-123d-441d-855c-69ae27d18078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string eaaadc84_0de1_4a6d_ba48_c394b5e484bf {
            get {
                return ResourceManager.GetString("eaaadc84-0de1-4a6d-ba48-c394b5e484bf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        public static string edd0ed36_48a1_40d5_b15c_4f72ecd03085 {
            get {
                return ResourceManager.GetString("edd0ed36-48a1-40d5-b15c-4f72ecd03085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string edfda485_050c_4881_9dea_906a3aca1ff6 {
            get {
                return ResourceManager.GetString("edfda485-050c-4881-9dea-906a3aca1ff6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string f562400a_d318_4ee3_bf9f_8e8879214b6b {
            get {
                return ResourceManager.GetString("f562400a-d318-4ee3-bf9f-8e8879214b6b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us.
        /// </summary>
        public static string fa0fc6df_5599_47df_adc1_54d604b4080b {
            get {
                return ResourceManager.GetString("fa0fc6df-5599-47df-adc1-54d604b4080b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload files.
        /// </summary>
        public static string fde8cfd5_5670_44c4_a5b9_0469b00e0b31 {
            get {
                return ResourceManager.GetString("fde8cfd5-5670-44c4-a5b9-0469b00e0b31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description is missing.
        /// </summary>
        public static string feeca1b6_3aee_4e53_8079_59f0baeb3e9c {
            get {
                return ResourceManager.GetString("feeca1b6-3aee-4e53-8079-59f0baeb3e9c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ffeee73c_ca11_4b14_bc87_f991da14edeb {
            get {
                return ResourceManager.GetString("ffeee73c-ca11-4b14-bc87-f991da14edeb", resourceCulture);
            }
        }
    }
}
