name: CI/CD with Terraform

on:
  push:
    branches:
      - Complete-CI/CD-with-Terraform-AWS

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_NONPROD }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_NONPROD }}
  TF_STATE_BUCKET_NAME: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
  PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
  PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PUBLIC }}
  AWS_REGION: us-east-1

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Run a one-line script
          run: echo Hello, world!
        - name: Run a multi-line script
          run: |
            echo Add other actions to build,
            echo test, and deploy your project.
        - name: java version
          run: java -version
        - name: maven version
          run: mvn --version
        - name: python version
          run: python --version
        - name: docker version
          run: docker -v
        - name: terraform version
          run: terraform --version
    deploy-infra:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_wrapper: false
        - name: Terraform init
          id: init
          run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME" -backend-config="region=us-east-1"
          working-directory: ./Tozawa.Client/terraform
        - name: Terraform Plan
          id: plan
          run: |-
            terraform plan \
            -var="region=us-east-1" \
            -var="public_key=$PUBLIC_SSH_KEY" \
            -var="private_key=$PRIVATE_SSH_KEY" \
            -var="key_name=deployer-key" \
            -out=PLAN
          working-directory: ./Tozawa.Client/terraform
        - name: Terraform Apply
          id: apply
          run: terraform apply PLAN
          working-directory: ./Tozawa.Client/terraform